// src/config/contracts.ts

/**
 * Contract ABIs and addresses for the deployed contracts on Arc Testnet.
 * 
 * This file is the single source of truth for:
 * - Contract addresses (from deployment)
 * - Contract ABIs (so ethers.js knows how to interact with them)
 */

// Import ABIs from the contract artifacts
// These JSON files were generated by Foundry during compilation
import PaymentPoolABI from '../../../contracts/out/PaymentPool.sol/PaymentPool.json' assert { type: 'json' };
import IntentVaultABI from '../../../contracts/out/IntentVault.sol/IntentVault.json' assert { type: 'json' };
import BatchSettlerABI from '../../../contracts/out/BatchSettler.sol/BatchSettler.json' assert { type: 'json' };

// Contract addresses from environment variables (loaded from .env)
export const PAYMENT_POOL_ADDRESS = process.env.PAYMENT_POOL_ADDRESS!;
export const INTENT_VAULT_ADDRESS = process.env.INTENT_VAULT_ADDRESS!;
export const BATCH_SETTLER_ADDRESS = process.env.BATCH_SETTLER_ADDRESS!;

// Export the ABIs (these are the contract interfaces)
// The .abi property extracts just the ABI array from the Foundry JSON
export const PaymentPoolABI_Interface = PaymentPoolABI.abi;
export const IntentVaultABI_Interface = IntentVaultABI.abi;
export const BatchSettlerABI_Interface = BatchSettlerABI.abi;

// Validation: make sure all addresses are set
if (!PAYMENT_POOL_ADDRESS || !INTENT_VAULT_ADDRESS || !BATCH_SETTLER_ADDRESS) {
  throw new Error('Missing contract addresses in .env file');
}

console.log('📋 Contract addresses loaded:');
console.log('  PaymentPool:', PAYMENT_POOL_ADDRESS);
console.log('  IntentVault:', INTENT_VAULT_ADDRESS);
console.log('  BatchSettler:', BATCH_SETTLER_ADDRESS);